name: quiz_lab
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  animated_floating_buttons: ^0.0.2
  audioplayers: ^5.1.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  change_app_package_name: ^1.1.0
  circular_countdown_timer: ^0.2.3
  cloud_firestore: ^4.8.5
  confetti: ^0.7.0
  connectivity_plus: ^2.3.6+1
  country_picker: ^2.0.11
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^5.3.3
  dotted_border: ^2.0.0+2
  file_picker: ^5.2.4
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  firebase_core_platform_interface: ^4.8.0
  firebase_messaging: ^14.6.8
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^15.1.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.10.0
  gallery_saver: ^2.3.2
  get: ^4.6.6
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.5
  http: ^0.13.4
  image_gallery_saver: ^2.0.3
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  introduction_screen: ^3.1.11
  lottie: ^2.3.1
  octo_image: ^1.0.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  pin_code_fields: ^7.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  share_plus: ^4.0.6
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  simple_animations: ^4.2.0
  slide_countdown: ^0.6.0
  url_launcher: ^6.0.20
  vibration: any
  wakelock: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - assets/animation/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
